### ISSUE TITLE
下载hrnetw32.pth到./log/后执行bash ./scripts/predict_test.sh时报错

### ISSUE THREAD

**Issue by yulin-yf** [Junjue-Wang/LoveDA#9]
您好，按照您Semantic_Segmentation/Readme里面的方法的1，2，3步执行后。在第三步执行
bash ./scripts/predict_test.sh时报错。

![83afafdb45718491ac1d02693eca8b0](https://user-images.githubusercontent.com/94375166/141935881-0bd044e1-07fe-4bde-ace6-dea650e3aed4.png)

请问我是差了什么步骤没有执行吗？

**Comment by Junjue-Wang** [comment]
感谢您指出代码的bug，这是我们在转换模型参数时候出的错误，现在我们已更新[predict.py](https://github.com/Junjue-Wang/LoveDA/blob/423e07f6f0108f91c6978cf30cb864fddaab384f/Semantic_Segmentation/predict.py#L32)脚本，请重新测试，若有问题，请继续联系我~

**Comment by yulin-yf** [comment]
谢谢，还有一个问题。执行predict，从网址下载模型时有报错。
![b04a7156a1998107eede3c6f8a40c54](https://user-images.githubusercontent.com/94375166/141955573-6e784870-3a41-4863-b7e1-4525c69e289c.png)
![3bd42a0621418981b4f69dc4e9f2022](https://user-images.githubusercontent.com/94375166/141955593-23436b8b-b7a6-4fed-b778-6fe74a67e28b.png)
然后手动去了这个网址https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/hrnetv2_w32-dc9eeb4f.pth，显示如下
![ca27478151d3f247b0f3e129173b43f](https://user-images.githubusercontent.com/94375166/141955924-0db9197d-e23d-4613-8734-93bf808e1640.png)

这个网址确定还可以下载模型吗，还是需要配置一下？

**Comment by Junjue-Wang** [comment]
这是open-mmlab的预训练模型，官网可以下载他们的模型，，您如果直接加载我们的参数，可以把pretrain设置为空 kingdrone ***@***.*** 签名由 网易邮箱大师 定制 在2021年11月16日 17:12，yulin-yf 写道： 谢谢，还有一个问题。执行predict，从网址下载模型时有报错。 然后手动去了这个网址https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/hrnetv2_w32-dc9eeb4f.pth，显示如下 这个网址确定还可以下载模型吗，还是需要配置一下？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yulin-yf** [comment]
非常感谢，成功解决啦

**Comment by Junjue-Wang** [comment]
不客气，也谢谢您找出我们代码中的bug，如有任何疑问请随时联系我~

**Comment by Junjue-Wang** [comment]
因为我训练的模型用了后处理，去掉了optim等参数。
用你自己的训练模型采用这种方式是对的。

**Comment by shata-wh** [comment]
> 

原来是这样，感谢解答！
